---
name: "Build"
on:
  workflow_dispatch:
    tags:
      - "v*"
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          sudo apt update
          sudo apt -y install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget libuuid-perl lxc \
          python3-software-properties

      - name: "Download and install DAB"
        run: |
           wget http://download.proxmox.com/debian/dists/bookworm/pve-no-subscription/binary-amd64/dab_3.5.0_all.deb
           sudo dpkg -i dab*
      - name: Git Clone Reposytory
        run: |
           git clone https://github.com/mikysal78/proxmox-ct-template-devuan-5.0.1.git devuan
           mv devuan/* .
      - name: Show info repo
        run: |
           echo "sono nella directory"
           pwd
           echo "Questi sono i files"
           ls -la
           
      - name: Compile
        run: |
          make

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            devuan-5.0-minimal_5.0.1_amd64.tar.gz
